language: node_js
node_js:
  - 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
cache:
  directories:
    - node_modules

before_install:
  - npm update
install:
  - npm install
before_script:
  - npm install -g surge
script:
  - npm run coveralls
  - npm run build

after_deploy:
  provider: surge
  skip_cleanup: true
  project: ./docs/
  domain: fadin.docs.surge.sh